### PR TITLE
fix(circleci): Set explicit node and npm versions for dev and circleci

### PR DESCRIPTION
**Pull request by sortelli**

### CODE REVIEW

**Comment by sortelli** [comment]
Hold on merging this until I've fully tested these changes on circle. I've already got an error simply trying to install a newer version of npm

**Comment by hitchcockwill** [comment]
It's also worth noting that any changes in `react-script/script/init.js` or `react-scripts/template/` will only affect new projects when they're created which means that you'll need to go in an manually make this same change in your application.

**Comment by sortelli** [comment]
> Note that you'll need to rebase from origin/next to get the new release script.

Just saw this note. I assume you did just this, this morning :)

**Comment by hitchcockwill** [comment]
Working on changing up the release process a bit based on feedback. Will post updates to #ureact-cra when this gets out.

**Pull request merged**
